2025-09-25 14:57:05,933 INFO    MainThread:25244 [wandb_setup.py:_flush():81] Current SDK version is 0.22.0
2025-09-25 14:57:05,933 INFO    MainThread:25244 [wandb_setup.py:_flush():81] Configure stats pid to 25244
2025-09-25 14:57:05,933 INFO    MainThread:25244 [wandb_setup.py:_flush():81] Loading settings from C:\Users\morli\.config\wandb\settings
2025-09-25 14:57:05,933 INFO    MainThread:25244 [wandb_setup.py:_flush():81] Loading settings from c:\Users\morli\Perso\Workshop2025\wandb\settings
2025-09-25 14:57:05,933 INFO    MainThread:25244 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-09-25 14:57:05,933 INFO    MainThread:25244 [wandb_init.py:setup_run_log_directory():686] Logging user logs to c:\Users\morli\Perso\Workshop2025\wandb\run-20250925_145705-f29910m6\logs\debug.log
2025-09-25 14:57:05,935 INFO    MainThread:25244 [wandb_init.py:setup_run_log_directory():687] Logging internal logs to c:\Users\morli\Perso\Workshop2025\wandb\run-20250925_145705-f29910m6\logs\debug-internal.log
2025-09-25 14:57:05,935 INFO    MainThread:25244 [wandb_init.py:monkeypatch_ipython():605] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000227EE235A90>
2025-09-25 14:57:05,935 INFO    MainThread:25244 [wandb_init.py:init():813] calling init triggers
2025-09-25 14:57:05,935 INFO    MainThread:25244 [wandb_init.py:init():818] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-09-25 14:57:05,935 INFO    MainThread:25244 [wandb_init.py:init():861] starting backend
2025-09-25 14:57:08,371 INFO    MainThread:25244 [wandb_init.py:init():864] sending inform_init request
2025-09-25 14:57:08,527 INFO    MainThread:25244 [wandb_init.py:init():872] backend started and connected
2025-09-25 14:57:08,530 INFO    MainThread:25244 [wandb_run.py:_label_probe_notebook():1330] probe notebook
2025-09-25 14:57:08,541 INFO    MainThread:25244 [wandb_run.py:_label_probe_notebook():1340] Unable to probe notebook: 'charmap' codec can't decode byte 0x8f in position 4900: character maps to <undefined>
2025-09-25 14:57:08,541 INFO    MainThread:25244 [wandb_init.py:init():942] updated telemetry
2025-09-25 14:57:08,584 INFO    MainThread:25244 [wandb_init.py:init():966] communicating run to backend with 90.0 second timeout
2025-09-25 14:57:09,921 INFO    MainThread:25244 [wandb_init.py:init():1017] starting run threads in backend
2025-09-25 14:57:10,062 INFO    MainThread:25244 [wandb_run.py:_console_start():2506] atexit reg
2025-09-25 14:57:10,063 INFO    MainThread:25244 [wandb_run.py:_redirect():2354] redirect: wrap_raw
2025-09-25 14:57:10,063 INFO    MainThread:25244 [wandb_run.py:_redirect():2423] Wrapping output streams.
2025-09-25 14:57:10,063 INFO    MainThread:25244 [wandb_run.py:_redirect():2446] Redirects installed.
2025-09-25 14:57:10,070 INFO    MainThread:25244 [wandb_init.py:init():1057] run started, returning control to user process
2025-09-25 14:57:10,071 INFO    MainThread:25244 [wandb_init.py:_post_run_cell_hook():575] [no run ID] resuming backend
2025-09-25 14:58:01,673 INFO    MainThread:25244 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-09-25 14:58:01,673 INFO    MainThread:25244 [wandb_init.py:_pre_run_cell_hook():564] [no run ID] pausing backend
2025-09-25 14:58:01,674 INFO    MainThread:25244 [wandb_init.py:_post_run_cell_hook():575] [no run ID] resuming backend
2025-09-25 14:58:01,681 INFO    MainThread:25244 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-09-25 14:58:01,682 INFO    MainThread:25244 [wandb_init.py:_pre_run_cell_hook():564] [no run ID] pausing backend
2025-09-25 14:58:01,691 INFO    MainThread:25244 [wandb_run.py:_finish():2272] finishing run mokiii-epsi/my-awesome-project/f29910m6
2025-09-25 14:58:01,691 INFO    MainThread:25244 [jupyter.py:save_history():480] not saving jupyter history
2025-09-25 14:58:01,691 INFO    MainThread:25244 [jupyter.py:save_ipynb():404] not saving jupyter notebook
2025-09-25 14:58:01,691 INFO    MainThread:25244 [wandb_init.py:_jupyter_teardown():590] cleaning up jupyter logic
2025-09-25 14:58:01,692 INFO    MainThread:25244 [wandb_run.py:_atexit_cleanup():2471] got exitcode: 0
2025-09-25 14:58:01,692 INFO    MainThread:25244 [wandb_run.py:_restore():2453] restore
2025-09-25 14:58:01,692 INFO    MainThread:25244 [wandb_run.py:_restore():2459] restore done
2025-09-25 14:58:02,837 INFO    MainThread:25244 [wandb_run.py:_footer_sync_info():3867] logging synced files
